[tool.poetry]
name = "documentation"
version = "0.1.0"
description = ""
authors = ["NicklasXYZ"]

[tool.poetry.dependencies]
python = "^3.9"
mkdocs-material = "^8.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
